In [19]:
import pandas as pd
import statsmodels.formula.api as smf

df = pd.read_csv('/home/desktop/Documentos/abacate.csv', header=0,  sep=';')
df.head()

,id,dataop,semana,semanaano,diaano,mercado,bairro,valor,status,dolar,tempmin,tempmax,amptemp,umidmax,umidmin,umidamp
0,1,2010-05-01,7,18,121,AGRICER,BOQUEIRAO,3.208182,FILIAL_333,1.7315,14.3,23.0,8.7,91.0,49.0,42.0
1,2,2010-05-01,7,18,121,AGRICER,CAPAO DA IMBUIA,3.208182,CIDADE_9,1.7315,14.3,23.0,8.7,91.0,49.0,42.0
2,3,2010-05-01,7,18,121,AGRICER,CIC,3.208182,FILIAL_321,1.7315,14.3,23.0,8.7,91.0,49.0,42.0
3,4,2010-05-01,7,18,121,AGRICER,BOQUEIRAO,3.208182,CIDADE_9,1.7315,14.3,23.0,8.7,91.0,49.0,42.0
4,5,2010-05-01,7,18,121,ALFA,SANTA FELICIDADE,3.208182,FILIAL_345,1.7315,14.3,23.0,8.7,91.0,49.0,42.0

In [25]:
estimativa = smf.ols(formula = 'valor ~  dolar', data = df)

modelo = estimativa.fit()

print(modelo.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  valor   R-squared:                       0.267
Model:                            OLS   Adj. R-squared:                  0.267
Method:                 Least Squares   F-statistic:                 1.623e+05
Date:                Tue, 19 Jul 2022   Prob (F-statistic):               0.00
Time:                        18:06:08   Log-Likelihood:            -6.9416e+05
No. Observations:              446518   AIC:                         1.388e+06
Df Residuals:                  446516   BIC:                         1.388e+06
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.9038      0.006    332.691      0.000       1.893       1.915
dolar          0.7733      0.002    402.823      0.000       0.769       0.777
==============================================================================
Omnibus:                   165114.733   Durbin-Watson:                   0.412
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           746456.755
Skew:                           1.775   Prob(JB):                         0.00
Kurtosis:                       8.246   Cond. No.                         11.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.