In [1]:
import pandas as pd
import statsmodels.formula.api as smf

df = pd.read_csv('/home/desktop/Documentos/hortfrut.csv', header=0,  sep=';')
df.head()

,ano,mes,dia,semana,semanaano,diaano,idbairro,idlocal,idproduto,valor,dolar,tempmin,tempmax,ampli,umidmax
0,2010,5,10,2,20,130,3,11,440,3.98,1.7833,9.8,15.8,6.0,92.0
1,2010,5,10,2,20,130,3,11,441,3.98,1.7833,9.8,15.8,6.0,92.0
2,2010,5,10,2,20,130,3,11,442,3.98,1.7833,9.8,15.8,6.0,92.0
3,2010,5,10,2,20,130,3,11,443,2.48,1.7833,9.8,15.8,6.0,92.0
4,2010,5,10,2,20,130,3,11,444,2.28,1.7833,9.8,15.8,6.0,92.0

In [2]:
estimativa = smf.ols(formula = 'valor ~  ano + diaano', data = df)

modelo = estimativa.fit()

print(modelo.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  valor   R-squared:                       0.036
Model:                            OLS   Adj. R-squared:                  0.036
Method:                 Least Squares   F-statistic:                 1.135e+04
Date:                Wed, 20 Jul 2022   Prob (F-statistic):               0.00
Time:                        10:21:31   Log-Likelihood:            -1.2366e+06
No. Observations:              599243   AIC:                         2.473e+06
Df Residuals:                  599240   BIC:                         2.473e+06
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -298.4010      2.035   -146.608      0.000    -302.390    -294.412
ano            0.1498      0.001    148.277      0.000       0.148       0.152
diaano        -0.0002   2.37e-05     -8.571      0.000      -0.000      -0.000
==============================================================================
Omnibus:                   220445.497   Durbin-Watson:                   1.595
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1006062.225
Skew:                           1.760   Prob(JB):                         0.00
Kurtosis:                       8.282   Cond. No.                     1.67e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.67e+06. This might indicate that there are
strong multicollinearity or other numerical problems.